bmm/mybioregions/urls.py
from django.conf.urls.defaults import *
from views import *

urlpatterns = patterns('',
    (r'^analysis/', include('analysis.urls')),
    (r'^finished/(?P<uid>[\w_]+)/', finished ),
)

bmm/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Include bioregions app urls
    (r'^mybioregions/', include('mybioregions.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
        
    # Include all lingcod app urls. Any urls above will overwrite the common urls below
    (r'', include('lingcod.common.urls')),

)

urlpatterns += patterns('',
    (r'^analysistools/', include('lingcod.analysistools.urls')),
    (r'^zonal/', include('lingcod.raster_stats.urls')),
)

bmm/mybioregions/models.py
from django.conf import settings
from django.db import models
from django.contrib.gis.db import models
from django.utils.html import escape
from lingcod.features.models import PolygonFeature, FeatureCollection
from lingcod.analysistools.models import Analysis
from lingcod.features import register, alternate
from lingcod.common.utils import asKml, get_logger
from lingcod.unit_converter.models import area_in_display_units
import os
import time
import math

logger = get_logger()

BIOREGION_SIZES = (
    ('VS', 'Very Small (2m Hectares)'),
    ('S', 'Small (5m Hectares)'),
    ('M', 'Medium (20m Hectares)'),
    ('L', 'Large (50m Hectares)'),
    ('VL', 'Very Large (100m Hectares)'),
    ('MVL', 'Very Very Large (200m Hectares)'),
    ('VVL', 'Very Very Very Large (300m Hectares)'),
)

SIZE_LOOKUP = { # in millions of Hectares
    'VS': 2, 
    'S': 5, 
    'M': 20,
    'L': 50,
    'VL': 100,
    'MVL': 200,
    'VVL': 300,
}

try:
    REMOVE_MAPSET_AFTER_RUN = settings.REMOVE_MAPSET_AFTER_RUN
except:
    REMOVE_MAPSET_AFTER_RUN = True

@register
class MyBioregion(Analysis):
    
    #Input Parameters
    input_starting_point = models.PointField(srid=settings.GEOMETRY_CLIENT_SRID, null=True, 
            blank=True, verbose_name="Bioregion Starting Point")
    input_temp_weight = models.FloatField(verbose_name='Value given to Temperature')
    input_precip_weight = models.FloatField(verbose_name='Value given to Precipitation')
    input_biomass_weight = models.FloatField(verbose_name='Value given to Vegetation')
    input_lang_weight = models.FloatField(verbose_name='Value given to Language')
    input_elev_weight = models.FloatField(verbose_name='Value given to Elevation')
    input_marine_weight = models.FloatField(verbose_name='Value given to Marine Environment')
    #input_dwater_weight = models.FloatField(verbose_name='Value given to Proximity to Major Waterbodies')
    input_bioregion_size = models.CharField(choices=BIOREGION_SIZES, max_length=3,
            verbose_name='Relative size of Bioregion', default='S')
    
    #Descriptors (name field is inherited from Analysis)
    description = models.TextField(null=True, blank=True)
    satisfied = models.BooleanField(default=False)
    
    # All output fields should be allowed to be Null/Blank
    output_geom = models.PolygonField(srid=settings.GEOMETRY_DB_SRID,
            null=True, blank=True, verbose_name="Bioregion Geometry")
    output_numruns = models.IntegerField(null=True, blank=True)
    output_initcost = models.FloatField(null=True, blank=True)
    output_finalcost = models.FloatField(null=True, blank=True)

    
    def run(self):
        from lingcod.analysistools.grass import Grass

        ### Setup
        g = Grass(settings.GRASS_LOCATION,
                gisbase=settings.GRASS_GISBASE,
                gisdbase=settings.GRASS_GISDBASE,
                autoclean=REMOVE_MAPSET_AFTER_RUN)
        g.verbose = not REMOVE_MAPSET_AFTER_RUN # go verbose only if we're not removing the mapset
        rasts = g.list()['rast']

        outdir = '/tmp'
        outbase = 'bioregion_%s_%s' % (str(time.time()).split('.')[0], self.pk)
        output = os.path.join(outdir,outbase+'.json')

        ### Input parameteres
        coords = self.input_starting_point.transform(settings.GEOMETRY_DB_SRID, clone=True)
        p_temp = float(self.input_temp_weight)
        p_precip = float(self.input_precip_weight)
        p_biomass = float(self.input_biomass_weight)
        p_lang = float(self.input_lang_weight)
        p_elev = float(self.input_elev_weight)
        p_marine = float(self.input_marine_weight)
        x = p_temp + p_precip + p_biomass + p_lang + p_elev + p_marine 
        p_land = x - p_marine
        if p_land < 1: p_land = 0.5 
        if p_marine < 1: p_marine = 0.1 

        ### Guess at initial max_cost to achieve a given size
        desired_size_mHa = SIZE_LOOKUP[self.input_bioregion_size] #million Hectares
        # regression, R^2 ~ 0.38 for 275 random samples
        intercept = 0 #464070
        max_cost = math.fabs((3162 * x * (desired_size_mHa ** 0.5))+intercept)
        self.output_initcost = max_cost

        ### Set GRASS region to the smallest window we can
        desired_size = 10000000000 * desired_size_mHa
        radius = math.sqrt(desired_size/math.pi) 
        buff = coords.buffer(radius*5) # to be safe against long skinny bioregions
        g.run('g.region rast=biomass_slope')
        g.run('g.region w=%d s=%d e=%d n=%d' % buff.extent )
        
        ### Get values for starting point
        start_values = get_raster_values(g, rasts, coords)
        start_values['ocean_slope'] = get_nearest_ocean_value(g, coords)

        ### MAGIC CONSTANTS
        dist_constant = 150.0 # increases cost of distance regardless of data variation
        mult_constant = 5 # exaggerates variation
        # land distance constant is inversely related to the ratio of land:marine (and vice versa for ocean)
        land_dist_const = dist_constant / (p_land/p_marine)
        marine_dist_const = mult_constant * dist_constant / (p_marine/p_land)
        ocean_mult = 50.0 / (p_marine/p_land)

        ### Land cost 
        g.run('r.mapcalc "weighted_land_slope = %s + ' % land_dist_const +
                            '(%s * pow(abs(%s - temp_slope),2))*%s + ' % (p_temp,start_values['temp_slope'],mult_constant)  + 
                            '(%s * pow(abs(%s - precip_slope),2))*%s + ' % (p_precip,start_values['precip_slope'],mult_constant)  + 
                            '(%s * pow(abs(%s - biomass_slope),2))*%s + ' % (p_biomass,start_values['biomass_slope'],mult_constant)  + 
                            '(%s * pow(abs(%s - elev_slope),2))*%s + ' % (p_elev,start_values['elev_slope'],mult_constant)  + 
                            '(%s * if(%s - lang_slope == 0, 0, 2500))*%s' % (p_lang,start_values['lang_slope'],mult_constant)  + 
                            '"')

        ### Marine Cost
        if p_marine >= 1:
            g.run('r.mapcalc "weighted_ocean_slope = %s + ' % marine_dist_const +
                            '(%s * pow(abs(%s - ocean_slope),2))*%s' % (p_marine, start_values['ocean_slope'],mult_constant)  + 
                            '"')

            ### Combined Cost
            g.run('r.mapcalc "weighted_combined_slope = if(isnull(weighted_ocean_slope),0,weighted_ocean_slope * %s) + ' % (ocean_mult,) + 
                  'if(isnull(weighted_land_slope),0,weighted_land_slope)"')
        else:
            # For Combined Cost - Don't include the ocean at all, just use the land slope
            g.run('g.rename rast=weighted_land_slope,weighted_combined_slope')

        g.run('r.colors -n -e map=weighted_combined_slope color=grey')
        try:
            img_path = os.path.join(settings.MEDIA_ROOT, 'bio_cost', self.uid + '.png') 
            if os.path.exists(img_path):
                os.remove(img_path)
            # -t only available in 6.4.1+
            if g.revision > 43635: 
                opt = '-t'
            else:
                opt = ''
            g.run('r.out.png %s input=weighted_combined_slope output=%s' % (opt, img_path) )
        except:
            pass

        # iterate over cost_distance analysis until we converge on a reasonable size
        tolerance = 0.15
        ratio = 0.0
        i = 0
        delta_zero_count = 0
        largest_area = desired_size
        overs = []
        overs_sizes = []
        unders = []
        unders_sizes = []
        while True:
            try:
                g.run('g.remove rast=cost1,bio_rast')
                g.run('r.cost --o -k input=weighted_combined_slope output=cost1 coordinate=%s,%s max_cost=%s' % \
                    (coords[0],coords[1],max_cost) )
                g.run('r.mapcalc "bio_rast=if(cost1 >= 0)"')
            except Exception, e:
                # should never happen, lets try that again
                logger.error("Whoa .. Grass failed on the the cost or mapcalc step... \n %s \n ... i=%s ... trying again" % (e,i))
                max_cost = max_cost * 1.001
                if i > 8:
                    # this is bad
                    raise e
                i += 1
                continue

            old_area = largest_area
            largest_area = get_cost_area(g, 'bio_rast')
            delta_area = largest_area - old_area

            ratio = desired_size/largest_area
            logger.debug("#%s ratio %s max_cost %s actual %s desired %s" % (i, 
                    ratio,
                    max_cost, 
                    int((largest_area/10000.0)/1000000.0),  
                    int((desired_size/10000.0)/1000000.0)))
            if ratio > (1-tolerance) and ratio < (1+tolerance):
                break 

            if ratio < 1.0 : 
                overs.append(max_cost)
                overs_sizes.append(largest_area)
            else:
                unders.append(max_cost)
                unders_sizes.append(largest_area)

            try:
                # estimate the placement between
                # highest underestimate and the lowest overestimate
                usd = desired_size - max(unders_sizes)
                osd = min(overs_sizes) - desired_size
                tsd = float(usd + osd)
                max_cost = max(unders) * osd/tsd + min(overs) * usd/tsd
            except ValueError:
                max_cost = max_cost * (ratio ** 0.67)

            if ratio < 0.99 and len(unders)==0: 
                # we are overestimating max_cost, try a very low cost 
                try:
                    max_cost = min(overs) / 10.0
                except:
                    max_cost = max_cost / 10.0

            if ratio > 1.01 and len(overs)==0: 

bmm/mybioregions/forms.py
from lingcod.features.forms import FeatureForm, SpatialFeatureForm
from mybioregions.models import MyBioregion, Folder
from lingcod.analysistools.widgets import SliderWidget, SimplePoint
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.gis.geos import fromstr
#from django.forms.widgets import RadioSelect
from models import *

class MyBioregionForm(FeatureForm):
    #might change the following to ModelChoiceField to pull city names from a model
    #also, might use different strategy altogether that allows users to simply select a point on a map as the starting point
    input_starting_point = forms.CharField(label="Bioregion Starting Point", widget=SimplePoint(title="Bioregion"))
    input_temp_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/sun.png'),
            label="Temperature")
    input_precip_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/rain.png'),
            label="Precipitation")
    input_biomass_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/veg.png'),
            label="Vegetation")
    input_lang_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/lang.png'),
            label="Human Language")
    input_elev_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/elev.png'),
            label="Elevation")
    input_marine_weight = forms.FloatField(min_value=0, max_value=100.0, initial=0,
            widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/marine.png'),
            label="Marine Environment")
    #input_dwater_weight = forms.FloatField(min_value=0, max_value=100.0, initial=50,
    #        widget=SliderWidget(min=0,max=100,step=1, show_number=False, image='bmm/img/dwater.png'),
    #        label="Proximity to Major Waterbodies")
        
    class Meta(FeatureForm.Meta):
        model = MyBioregion
        exclude = list(FeatureForm.Meta.exclude)
        for f in model.output_fields():
            exclude.append(f.attname)

class FolderForm(FeatureForm):
    class Meta(FeatureForm.Meta):
        model = Folder
    
class PlaceholderForm(SpatialFeatureForm):
    class Meta(SpatialFeatureForm.Meta):
        model = Placeholder

bmm/mybioregions/views.py
from lingcod.common import utils
from lingcod.shapes.views import ShpResponder
from lingcod.features.views import get_object_for_viewing, get_object_for_editing
from django.http import HttpResponse
from django.template.defaultfilters import slugify

def finished(request, uid):
    bio = get_object_for_editing(request,uid)
    bio.satisfied = True
    bio.save(rerun=False)
    return HttpResponse("%s finished" % uid, status=200)

def bmm_shapefile(request, instances):
    from mybioregions.models import MyBioregion, Folder, BioregionShapefile
    bios = []
    for inst in instances:
        viewable, response = inst.is_viewable(request.user)
        if not viewable:
            return response

        if isinstance(inst, MyBioregion):
            inst.convert_to_shp()
            bios.append(inst)
        elif isinstance(inst, Folder):
            for bio in inst.feature_set(recurse=True,feature_classes=[MyBioregion]):
                bio.convert_to_shp()
                bios.append(bio)
        else:
            pass # ignore anything else

    filename = '_'.join([slugify(inst.name) for inst in instances])
    pks = [bio.pk for bio in bios]
    qs = BioregionShapefile.objects.filter(bio_id_num__in=pks)
    if len(qs) == 0:
        return HttpResponse(
            "Nothing in the query set; you don't want an empty shapefile", 
            status=404
        )
    shp_response = ShpResponder(qs)
    shp_response.file_name = slugify(filename[0:8])
    return shp_response()

bmm/mybioregions/templates/mybioregion/form.html
{% extends "common/panel.html" %}
{% block title %}{{title}}{% endblock %}
{% block panel %}
<script type="text/javascript" charset="utf-8">
    lingcod.onShow(function(){
        lingcod.setupForm($('#featureform'));

        var step = 1;
        var max_step = 3;
        function validate(step) {
            if (step == 1) {
                if ($('#id_input_starting_point').val() == '') {
                    alert("You must set a starting point to proceed to step 2");
                    return false;
                }
            }
            return true
        }; 

        function wizard(action) {
            if (step > 1 && action == 'prev') {
                step -= 1;
            }
            if (step < max_step && action == 'next') {
                if (validate(step)) {
                    step += 1;
                }
            }
            $('div.step').each(function(index) {
                $(this).hide();
            });

            $('div#step' + step).show();

            if (step == 1) {
                $('#button_prev').hide();
            } else {
                $('#button_prev').show();
            }

            if (step == max_step) {
                $('#button_next').hide();
                $('.submit_button').show();
            } else {
                $('#button_next').show();
                $('.submit_button').hide();
            }
        };
        $('#button_prev').click( function() { wizard('prev'); });
        $('#button_next').click( function() { wizard('next'); });
        wizard();

        $('ul.errorlist').each( function() {
                $('div#error_bar').html("<ul class='errorlist'><li>We encountered an error while processing your bioregion. Can you recheck the steps and make sure you've filled in all the required information?</li></ul>");
        });

        $('img.paraminfo').each( function() {
            var id = $(this).attr('id');
            var text = "none";
            switch(id) {
                case 'info_temp':
                    text = "Temperature takes into account both minimum temperature and temperature range.";
                    break;
                case 'info_precip':
                    text = "Precipitation takes into account the average annual rainfall.";
                    break;
                case 'info_biomass':
                    text = "Vegetation takes into account the total biomass of the region.";
                    break;
                case 'info_lang':
                    text = "Language takes into account the primary spoken language in a region.";
                    break;
                case 'info_elev':
                    text = "Elevation takes into account the land elevation above sea level";
                    break;
                case 'info_marine':
                    text = "Marine takes into account sea surface temperature, bathymetry and distance to shoreline.";
                    break;
                default:
                    $(this).hide();
            }
            if (text!='none') {
                $(this).qtip({
                    content: text, 
                    show: { 
                        delay: 0,
                        when: { event: 'mouseover' } 
                    },
                    hide: { when: {event: 'mouseleave'} },
                    style: { name: 'light' }
                });
            }
        });
            
    });
</script>

<style type="text/css">
div .field > label { font-size: 12px; display: inline; }
div .step { 
    -moz-box-shadow: 5px 5px 5px #ddd;
    -webkit-box-shadow: 5px 5px 5px #ddd;
    box-shadow: 5px 5px 5px #ddd; 
    -moz-border-radius: 6px;
    -webkit-border-radius: 6px;
    -khtml-border-radius: 6px;
    border-radius: 6px;
    border: 1px #ddd solid;
    padding: 6px;
    margin-top: 4px;
    margin-bottom: 8px;
    background-color: white; 
    background-repeat: no-repeat;
    min-height: 54px;
}
div .inputfield { padding-bottom: 14px; padding-left: 66px; }
span.form-image { float: left; margin-left: -66px; }
span.form-image > img { width:46px; height:46px; }
</style>

{% if form.media %} {{ form.media }} {% endif %}
<h1>{{ title }}</h1>
<form id="featureform" action="{{action}}" method="post"> 
    {% for hidden in form.hidden_fields %}
    <div style="display:none;">
        {{ hidden.errors }}
    </div>
    {{ hidden }}
    {% endfor %}


  <div id="error_bar"></div>
  
  <div class="step" id="step1">
    <h3> Step 1 of 3 </h3>
    <p>First, <strong>locate your area of interest</strong> on the interactive map to the right.
    <p>Second, <strong>set your starting point</strong> 
       by clicking the button below, then clicking the location on the map. </p>
    <div id="start">
        <div class="field required">
            <!-- {{ form.input_starting_point.label_tag }} -->
            {{ form.input_starting_point.errors }}
            {{ form.input_starting_point }}            
        </div>
    </div>
    <p><a id="displayText" href="javascript:toggleDiv('starting_point');">What is the starting point?</a>
    <div id="starting_point" style="display: none">
      <p>The starting point is the "center" of your bioregion; the hub which embodies the character of your bioregion. 
         The resulting bioregion map will be drawn to include nearby land that exhibits similar characteristics.</p>
    </div>
    <p><a id="displayText" href="javascript:toggleDiv('GoogleEarth');">New to Google Earth?</a>
    <div id="GoogleEarth" style="display: none">
      <p>To move around the map, use the navigation controls in the upper-right corner of the map. 
         You can also use the mouse and/or keyboard to navigate; 
         for more information, please visit the <a target="_blank" href="http://earth.google.com/support/bin/answer.py?answer=176674#zoom_mouse">Google Earth documentation</a>.</p>
    </div>
    
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script type="text/javascript">
  function toggleDiv(divId) {
     $("#"+divId).toggle();
  }
  </script>

        
      
  </div>

  <div class="step" id="step2">
    <h3> Step 2 of 3 </h3>
      <p> <strong>Specify the <em>relative importance</em> of the following parameters</strong>; in other words, to what extent do these parameters define your bioregion? </p>
      <p> For example, if you slide the temperature parameter to the right, your bioregion shape will be more likely to include areas with similar temperature characteristics to your starting point. </p>
    <div class="inputfield" id="temp">
        <div class="field required">
            {{ form.input_temp_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_temp" class="paraminfo"/>
            {{ form.input_temp_weight.errors }}
            {{ form.input_temp_weight }}            
        </div>
    </div>
    <div class="inputfield" id="precip">
        <div class="field required">
            {{ form.input_precip_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_precip" class="paraminfo"/>
            {{ form.input_precip_weight.errors }}
            {{ form.input_precip_weight }}            
        </div>
    </div>
    <div class="inputfield" id="veg">
        <div class="field required">
            {{ form.input_biomass_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_biomass" class="paraminfo"/>
            {{ form.input_biomass_weight.errors }}
            {{ form.input_biomass_weight }}            
        </div>
    </div>
    <div class="inputfield" id="lang">
        <div class="field required">
            {{ form.input_lang_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_lang" class="paraminfo"/>
            {{ form.input_lang_weight.errors }}
            {{ form.input_lang_weight }}            
        </div>
    </div>
    <div class="inputfield" id="elev">
        <div class="field required">
            {{ form.input_elev_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_elev" class="paraminfo"/>
            {{ form.input_elev_weight.errors }}
            {{ form.input_elev_weight }}            
        </div>
    </div>
    <div class="inputfield" id="marine">
        <div class="field required">
            {{ form.input_marine_weight.label_tag }} <img src="/media/bmm/img/info.png" id="info_marine" class="paraminfo"/>
            {{ form.input_marine_weight.errors }}
            {{ form.input_marine_weight }}            
        </div>
    </div>
    <div class="inputfield" id="size">
        <div class="field required">
            {{ form.input_bioregion_size.label_tag }} <img src="/media/bmm/img/info.png" id="info_size" class="paraminfo"/>
            {{ form.input_bioregion_size.errors }}
            <br/>
            {{ form.input_bioregion_size }}            
        </div>
    </div>
  </div>

<div class="step" id="step3">
    <h3> Step 3 of 3 </h3>
    <p> <strong>Provide a name</strong> to identify your bioregion </p>
    <div class="field required">
        {{ form.name.label_tag }}
        {{ form.name.errors }}
        {{ form.name }}            
    </div>
    <p> Optionally, you may add notes and further descriptions here.  </p>
    <div>
        {{ form.description.label_tag }}
        {{ form.description.errors }}
        {{ form.description }}            
    </div>
</div>

<p><input type="submit" value="submit"></p>
</form>


<div class="wizard_nav" style="width:100%">
    <a href="#" class="button" style="float:left;" onclick="this.blur(); return false;" id="button_prev"><span>&lt; Previous</span></a>
    <a href="#" class="button" style="float:right;" onclick="this.blur(); return false;" id="button_next"><span>Next &gt;</span></a>
</div>

<div>
    <a href="#" class="cancel_button button red" onclick="this.blur(); return false;"><span>Cancel</span></a>
    <a href="#" class="submit_button button" onclick="this.blur(); return false;"><span>Submit</span></a>
</div>


{% endblock %}